-- Add Instagram AI analysis caching columns to business_insights table
-- Similar to gbp_ai_analysis, but for Instagram

ALTER TABLE business_insights
ADD COLUMN IF NOT EXISTS instagram_ai_analysis JSONB,
ADD COLUMN IF NOT EXISTS instagram_ai_analysis_generated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS instagram_username TEXT;

COMMENT ON COLUMN business_insights.instagram_ai_analysis IS 'Cached AI analysis for Instagram, generated by OpenAI.';
COMMENT ON COLUMN business_insights.instagram_ai_analysis_generated_at IS 'Timestamp when the Instagram AI analysis was last generated.';
COMMENT ON COLUMN business_insights.instagram_username IS 'Instagram username used for this analysis.';

